### PR TITLE
NTT: Simplify computation of zeta index

### LINKED ISSUE #828: Remove scan-build false positive
A plain `scan-build make OPT=0` fails, complaining about a non-issue in `poly.c` about the loading of the zeta table. Yet, we need to find a way to make `scan-build` happy.

### PR DESCRIPTION
**Pull request by hanno-becker**
The n-th layer of the NTT needs the zeta table entries at indices `2^(n-1)..2^n-1`. Previously, the initial index was computed using a division by the `len` parameter, upholding the status of the `layer` parameter as a pure ghost variable only needed for the specification, but not the code itself.

This commit gives up the status of `layer` as a ghost variable and instead uses it to compute the initial zeta index using a shift instead of a division.

While `len` is not secret and there is, thus, no risk of information leakage when a `div` instruction is used, it still seems cleaner and faster to work with a shift.

* Resolves #828 

Suggested-by: @rod-chapman

### CODE REVIEW

**Comment by rod-chapman** [comment]
CI looks good. Happy to merge.

File: mlkem/ntt.c [hunk 1]
```diff
@@ -172,9 +170,9 @@ __contract__(
   ensures(array_abs_bound(r, 0, MLKEM_N, MLKEM_Q)))
 {
   unsigned start, k;
-  /* `layer` is a ghost variable used only in the specification */
-  ((void)layer);
-  k = MLKEM_N / len - 1;
+  /* Twiddle factors for layer n are at indices 2^(n-1)..2^n-1.
+   * The inverse NTT uses them in backwards order. */
+  k = (1u << layer) - 1;
```
Comment (rod-chapman) [inline mlkem/ntt.c:175]: Looks good. CI is clean.

**Review by rod-chapman — APPROVED** [review]
A welcome simplification, and also removes the odd "ghost" status the layer parameter.

**Review by mkannwischer — CHANGES_REQUESTED** [review]
Since layer is now no longer a ghost variable, please adjust the comments above the function accordingly.

File: mlkem/poly.c [hunk 2]
```diff
@@ -397,17 +396,17 @@ __contract__(
 MLK_INTERNAL_API
```
Comment (hanno-becker) [inline mlkem/poly.c:396]: @mkannwischer Can you add a comment here? e.g.
```
/* Reference: `ntt()` in the reference implementation.
 * - Iterate over `layer` instead of `len` in the outer loop */
```

Comment (mkannwischer) [reply mlkem/poly.c:398]: done.

**Review by mkannwischer — APPROVED** [review]
LGTM
